#!/bin/bash

. ./.config_recreacion_ambiente

clear

echo
echo "Instancia y usuario:"
echo "  DBNAME     = $DBNAME"
echo "  USUARIO_DB = $USUARIO_DB"
echo

echo "Creando lenguaje"
psql -d $DBNAME -U $USUARIO_DB < 00050_language.sql > 00060_language.txt 2> 00070_language.txt

./00100_drop_table.sh

echo "Borrando tablas"
psql -d $DBNAME -U $USUARIO_DB < 00110_drop_table.sql > 00120_drop_table.txt

echo "Creando tablas"
psql -d $DBNAME -U $USUARIO_DB < 00200_tablas.sql > 00210_tablas.txt

./00300_vistas_cortas.sh

echo "Creando vistas cortas"
psql -d $DBNAME -U $USUARIO_DB < 00310_vistas_cortas.sql > 00320_vistas_cortas.txt

echo "Poniendo secuencias al dia"
./00700_secuencias.sh

cd 01500_funciones_almacenadas

echo "Creando funciones"

echo "  00100_f_valida_usuario"
psql -d $DBNAME -U $USUARIO_DB < 00100_f_valida_usuario.sql > 00110_f_valida_usuario.txt

echo "  00200_f_crear_datos_holding"
psql -d $DBNAME -U $USUARIO_DB < 00200_f_crear_datos_holding.sql > 00210_f_crear_datos_holding.txt

echo "  00300_f_dv_rut_cl"
psql -d $DBNAME -U $USUARIO_DB < 00300_f_dv_rut_cl.sql > 00310_f_dv_rut_cl.txt

echo "  00400_f_validar_dv_pers"
psql -d $DBNAME -U $USUARIO_DB < 00400_f_validar_dv_pers.sql > 00410_f_validar_dv_pers.txt

echo "  00500_f_mandar_aviso_por_dole"
psql -d $DBNAME -U $USUARIO_DB < 00500_f_mandar_aviso_por_dole.sql > 00510_f_mandar_aviso_por_dole.txt

echo "  00600_f_limpia"
psql -d $DBNAME -U $USUARIO_DB < 00600_f_limpia.sql > 00610_f_limpia.txt

echo "  00700_f_validar_cove"
psql -d $DBNAME -U $USUARIO_DB < 00700_f_validar_cove.sql > 00710_f_validar_cove.txt

echo "  00800_f_validar_nove"
psql -d $DBNAME -U $USUARIO_DB < 00800_f_validar_nove.sql > 00810_f_validar_nove.txt

echo "  00900_f_validar_vent"
psql -d $DBNAME -U $USUARIO_DB < 00900_f_validar_vent.sql > 00910_f_validar_vent.txt

echo "  01000_f_copiar_cove_a_nove"
psql -d $DBNAME -U $USUARIO_DB < 01000_f_copiar_cove_a_nove.sql > 01010_f_copiar_cove_a_nove.txt

echo "  01100_f_copiar_nove_a_vent"
psql -d $DBNAME -U $USUARIO_DB < 01100_f_copiar_nove_a_vent.sql > 01110_f_copiar_nove_a_vent.txt

echo "  01200_f_validar_cove_ins"
psql -d $DBNAME -U $USUARIO_DB < 01200_f_validar_cove_ins.sql > 01210_f_validar_cove_ins.txt

echo "  01300_f_validar_nove_ins"
psql -d $DBNAME -U $USUARIO_DB < 01300_f_validar_nove_ins.sql > 01310_f_validar_nove_ins.txt

echo "  01400_f_validar_vent_ins"
psql -d $DBNAME -U $USUARIO_DB < 01400_f_validar_vent_ins.sql > 01410_f_validar_vent_ins.txt

echo "  01500_f_datos_linea_vta"
psql -d $DBNAME -U $USUARIO_DB < 01500_f_datos_linea_vta.sql > 01510_f_datos_linea_vta.txt

echo "  01600_f_stock_producto"
psql -d $DBNAME -U $USUARIO_DB < 01600_f_stock_producto.sql > 01610_f_stock_producto.txt

echo "  01700_f_completar_rubro_empresa"
psql -d $DBNAME -U $USUARIO_DB < 01700_f_completar_rubro_empresa.sql > 01710_f_completar_rubro_empresa.txt

echo "  01800_f_crear_datos_empresa"
psql -d $DBNAME -U $USUARIO_DB < 01800_f_crear_datos_empresa.sql > 01810_f_crear_datos_empresa.txt

echo "  01900_f_datos_producto"
psql -d $DBNAME -U $USUARIO_DB < 01900_f_datos_producto.sql > 01910_f_datos_producto.txt

echo "  02000_f_registrar_precio_bitacora"
psql -d $DBNAME -U $USUARIO_DB < 02000_f_registrar_precio_bitacora.sql > 02010_f_registrar_precio_bitacora.txt

echo "  02100_f_rebajar_stock"
psql -d $DBNAME -U $USUARIO_DB < 02100_f_rebajar_stock.sql > 02110_f_rebajar_stock.txt

echo "  02200_f_valor_parametro"
psql -d $DBNAME -U $USUARIO_DB < 02200_f_valor_parametro.sql > 02210_f_valor_parametro.txt

echo "  02300_f_validar_requ_ins"
psql -d $DBNAME -U $USUARIO_DB < 02300_f_validar_requ_ins.sql > 02310_f_validar_requ_ins.txt

echo "  02400_f_validar_requ"
psql -d $DBNAME -U $USUARIO_DB < 02400_f_validar_requ.sql > 02410_f_validar_requ.txt

echo "  02500_f_profundidad_unte"
psql -d $DBNAME -U $USUARIO_DB < 02500_f_profundidad_unte.sql > 02510_f_profundidad_unte.txt

echo "  02600_f_poblar_unte_profundidad"
psql -d $DBNAME -U $USUARIO_DB < 02600_f_poblar_unte_profundidad.sql > 02610_f_poblar_unte_profundidad.txt

echo "  02700_f_copiar_requ_a_orco"
psql -d $DBNAME -U $USUARIO_DB < 02700_f_copiar_requ_a_orco.sql > 02710_f_copiar_requ_a_orco.txt

echo "  02800_f_validar_orco"
psql -d $DBNAME -U $USUARIO_DB < 02800_f_validar_orco.sql > 02810_f_validar_orco.txt

echo "  02900_f_situacion_orco"
psql -d $DBNAME -U $USUARIO_DB < 02900_f_situacion_orco.sql > 02910_f_situacion_orco.txt

echo "  03000_f_validar_reco"
psql -d $DBNAME -U $USUARIO_DB < 03000_f_validar_reco.sql > 03010_f_validar_reco.txt

echo "  03100_f_impedir_upd_y_del_en_derc"
psql -d $DBNAME -U $USUARIO_DB < 03100_f_impedir_upd_y_del_en_derc.sql > 03110_f_impedir_upd_y_del_en_derc.txt

echo "  03300_f_aumentar_stock_x_reco"
psql -d $DBNAME -U $USUARIO_DB < 03300_f_aumentar_stock_x_reco.sql > 03310_f_aumentar_stock_x_reco.txt

echo "  03400_f_validar_rega_ins"
psql -d $DBNAME -U $USUARIO_DB < 03400_f_validar_rega_ins.sql > 03410_f_validar_rega_ins.txt

echo "  03500_f_validar_rega_upd"
psql -d $DBNAME -U $USUARIO_DB < 03500_f_validar_rega_upd.sql > 03510_f_validar_rega_upd.txt

echo "  03600_f_puede_borrar_registro"
psql -d $DBNAME -U $USUARIO_DB < 03600_f_puede_borrar_registro.sql > 03610_f_puede_borrar_registro.txt

echo "  03700_f_validar_decv"
psql -d $DBNAME -U $USUARIO_DB < 03700_f_validar_decv.sql > 03710_f_validar_decv.txt

echo "  03800_f_validar_denv"
psql -d $DBNAME -U $USUARIO_DB < 03800_f_validar_denv.sql > 03810_f_validar_denv.txt

echo "  03900_f_validar_email"
psql -d $DBNAME -U $USUARIO_DB < 03900_f_validar_email.sql > 03910_f_validar_email.txt

echo "  04000_f_perfil_padre_requ"
psql -d $DBNAME -U $USUARIO_DB < 04000_f_perfil_padre_requ.sql > 04010_f_perfil_padre_requ.txt

echo "  04100_f_perfiles_hijo_requ"
psql -d $DBNAME -U $USUARIO_DB < 04100_f_perfiles_hijo_requ.sql > 04110_f_perfiles_hijo_requ.txt

echo "  04200_f_perfil_puede_crear_requ"
psql -d $DBNAME -U $USUARIO_DB < 04200_f_perfil_puede_crear_requ.sql > 04210_f_perfil_puede_crear_requ.txt

echo "  04300_f_validar_uspe_ins_upd"
psql -d $DBNAME -U $USUARIO_DB < 04300_f_validar_uspe_ins_upd.sql > 04310_f_validar_uspe_ins_upd.txt

echo "  04400_f_generar_balance"
psql -d $DBNAME -U $USUARIO_DB < 04400_f_generar_balance.sql > 04410_f_generar_balance.txt

echo "  04500_f_contabilizar_ventas"
psql -d $DBNAME -U $USUARIO_DB < 04500_f_contabilizar_ventas.sql > 04510_f_contabilizar_ventas.txt

echo "  04600_f_validar_estructura_username"
psql -d $DBNAME -U $USUARIO_DB < 04600_f_validar_estructura_username.sql > 04610_f_validar_estructura_username.txt

echo "  04700_f_es_posible_cerrar_peco"
psql -d $DBNAME -U $USUARIO_DB < 04700_f_es_posible_cerrar_peco.sql > 04710_f_es_posible_cerrar_peco.txt

echo "  04800_f_cerrar_peco"
psql -d $DBNAME -U $USUARIO_DB < 04800_f_cerrar_peco.sql > 04810_f_cerrar_peco.txt

echo "  04900_f_contabilizar_compras"
#psql -d $DBNAME -U $USUARIO_DB < 04900_f_contabilizar_compras.sql > 04910_f_contabilizar_compras.txt

echo "  05000_f_datos_servicio"
psql -d $DBNAME -U $USUARIO_DB < 05000_f_datos_servicio.sql > 05010_f_datos_servicio.txt

echo "  05100_f_datos_direccion_cliente"
psql -d $DBNAME -U $USUARIO_DB < 05100_f_datos_direccion_cliente.sql > 05110_f_datos_direccion_cliente.txt

echo "  05200_ultimo_dia"
psql -d $DBNAME -U $USUARIO_DB < 05200_ultimo_dia.sql > 05210_ultimo_dia.txt

echo "  05300_f_aumentar_stock_x_comp"
psql -d $DBNAME -U $USUARIO_DB < 05300_f_aumentar_stock_x_comp.sql > 05310_f_aumentar_stock_x_comp.txt

cd ..

cd 01600_triggers

echo "Creando triggers"

echo "  00100_trg_after_ins_grem"
psql -d $DBNAME -U $USUARIO_DB < 00100_trg_after_ins_grem.sql > 00110_trg_after_ins_grem.txt

echo "  00200_trg_before_ins_upd_pers"
psql -d $DBNAME -U $USUARIO_DB < 00200_trg_before_ins_upd_pers.sql > 00210_trg_before_ins_upd_pers.txt

echo "  00300_trg_before_upd_cove"
psql -d $DBNAME -U $USUARIO_DB < 00300_trg_before_upd_cove.sql > 00310_trg_before_upd_cove.txt

echo "  00400_trg_before_upd_nove"
psql -d $DBNAME -U $USUARIO_DB < 00400_trg_before_upd_nove.sql > 00410_trg_before_upd_nove.txt

echo "  00500_trg_before_upd_vent"
psql -d $DBNAME -U $USUARIO_DB < 00500_trg_before_upd_vent.sql > 00510_trg_before_upd_vent.txt

echo "  00600_trg_after_upd_cove"
psql -d $DBNAME -U $USUARIO_DB < 00600_trg_after_upd_cove.sql > 00610_trg_after_upd_cove.txt

echo "  00700_trg_after_upd_nove"
psql -d $DBNAME -U $USUARIO_DB < 00700_trg_after_upd_nove.sql > 00710_trg_after_upd_nove.txt

echo "  00800_trg_before_ins_cove"
psql -d $DBNAME -U $USUARIO_DB < 00800_trg_before_ins_cove.sql > 00810_trg_before_ins_cove.txt

echo "  00900_trg_before_ins_nove"
psql -d $DBNAME -U $USUARIO_DB < 00900_trg_before_ins_nove.sql > 00910_trg_before_ins_nove.txt

echo "  01000_trg_before_ins_vent"
psql -d $DBNAME -U $USUARIO_DB < 01000_trg_before_ins_vent.sql > 01010_trg_before_ins_vent.txt

echo "  01100_trg_before_ins_empr"
psql -d $DBNAME -U $USUARIO_DB < 01100_trg_before_ins_empr.sql > 01110_trg_before_ins_empr.txt

echo "  01200_trg_after_ins_empr"
psql -d $DBNAME -U $USUARIO_DB < 01200_trg_after_ins_empr.sql > 01210_trg_after_ins_empr.txt

echo "  01300_trg_after_ins_upd_delp"
psql -d $DBNAME -U $USUARIO_DB < 01300_trg_after_ins_upd_delp.sql > 01310_trg_after_ins_upd_delp.txt

echo "  01400_trg_after_upd_vent"
psql -d $DBNAME -U $USUARIO_DB < 01400_trg_after_upd_vent.sql > 01410_trg_after_upd_vent.txt

echo "  01500_trg_before_upd_requ"
psql -d $DBNAME -U $USUARIO_DB < 01500_trg_before_upd_requ.sql > 01510_trg_before_upd_requ.txt

echo "  01600_trg_before_ins_requ"
psql -d $DBNAME -U $USUARIO_DB < 01600_trg_before_ins_requ.sql > 01610_trg_before_ins_requ.txt

echo "  01700_trg_after_ins_unte"
psql -d $DBNAME -U $USUARIO_DB < 01700_trg_after_ins_unte.sql > 01710_trg_after_ins_unte.txt

echo "  01800_trg_after_upd_requ"
psql -d $DBNAME -U $USUARIO_DB < 01800_trg_after_upd_requ.sql > 01810_trg_after_upd_requ.txt

echo "  01900_trg_before_upd_orco"
psql -d $DBNAME -U $USUARIO_DB < 01900_trg_before_upd_orco.sql > 01910_trg_before_upd_orco.txt

echo "  02000_trg_before_ins_reco"
psql -d $DBNAME -U $USUARIO_DB < 02000_trg_before_ins_reco.sql > 02010_trg_before_ins_reco.txt

echo "  02100_trg_before_upd_y_del_derc"
psql -d $DBNAME -U $USUARIO_DB < 02100_trg_before_upd_y_del_derc.sql > 02110_trg_before_upd_y_del_derc.txt

echo "  02300_trg_after_ins_derc"
psql -d $DBNAME -U $USUARIO_DB < 02300_trg_after_ins_derc.sql > 02310_trg_after_ins_derc.txt

echo "  02400_trg_before_ins_rega"
psql -d $DBNAME -U $USUARIO_DB < 02400_trg_before_ins_rega.sql > 02410_trg_before_ins_rega.txt

echo "  02500_trg_before_upd_rega"
psql -d $DBNAME -U $USUARIO_DB < 02500_trg_before_upd_rega.sql > 02510_trg_before_upd_rega.txt

echo "  02600_trg_before_ins_upd_del_decv"
psql -d $DBNAME -U $USUARIO_DB < 02600_trg_before_ins_upd_del_decv.sql > 02610_trg_before_ins_upd_del_decv.txt

echo "  02700_trg_before_ins_upd_del_denv"
psql -d $DBNAME -U $USUARIO_DB < 02700_trg_before_ins_upd_del_denv.sql > 02710_trg_before_ins_upd_del_denv.txt

echo "  02900_trg_before_ins_upd_uspe"
psql -d $DBNAME -U $USUARIO_DB < 02900_trg_before_ins_upd_uspe.sql > 02910_trg_before_ins_upd_uspe.txt

echo "  03000_trg_before_ins_upd_usua"
psql -d $DBNAME -U $USUARIO_DB < 03000_trg_before_ins_upd_usua.sql > 03010_trg_before_ins_upd_usua.txt

echo "  03100_trg_after_ins_deco"
psql -d $DBNAME -U $USUARIO_DB < 03100_trg_after_ins_deco.sql > 03110_trg_after_ins_deco.txt

cd ..

echo "Poblando datos iniciales"
psql -d $DBNAME -U $USUARIO_DB < 00600_datos_iniciales.sql > 00610_datos_iniciales.txt

echo "Poniendo secuencias al dia"
./00700_secuencias.sh

#echo "Creando tablas extra ERP"
#psql -d $DBNAME -U $USUARIO_DB < 01800_tablas_extra_ERP.sql > 01810_tablas_extra_ERP.txt

#echo "Poblando tabla tablas_secuencias"
#./01900_poblar_tase.sh

#psql -d $DBNAME -U $USUARIO_DB < 01910_poblar_tase.sql > 01920_poblar_tase.txt

#echo "Poblando tablas fode y fide"
#psql -d $DBNAME -U $USUARIO_DB < 02000_poblar_fode_fide.sql > 02010_poblar_fode_fide.txt

echo "Creando vistas **complejas**"
psql -d $DBNAME -U $USUARIO_DB < 02100_vistas_tablas_complejas.sql > 02110_vistas_tablas_complejas.txt

echo "Insertando perf, prog, pepr"
psql -d $DBNAME -U $USUARIO_DB < 02200_perf_prog_pepr.sql > 02210_perf_prog_pepr.txt

echo "Vista perfilamiento"
psql -d $DBNAME -U $USUARIO_DB < 02300_vista_perfilamiento.sql > 02310_vista_perfilamiento.txt

echo "Creando fks idusuacrearegistro"
psql -d $DBNAME -U $USUARIO_DB < 02400_crea_fks_idusuacrearegistro.sql > 02410_crea_fks_idusuacrearegistro.txt

echo "Poniendo secuencias al dia"
./00700_secuencias.sh

echo "Insertando datos de prueba (ficticios)"
psql -d $DBNAME -U $USUARIO_DB < 99000_datos_de_prueba.sql > 99010_datos_de_prueba.txt

echo "Insertando datos de SA-JJM"
psql -d $DBNAME -U $USUARIO_DB < 99100_otros_datos_SA_JJM.sql > 99110_otros_datos_SA_JJM.txt

echo "Poniendo secuencias al dia"
./00700_secuencias.sh

echo "Insertando productos de JJM"
psql -d $DBNAME -U $USUARIO_DB < 99200_insertar_prods_JJM.sql > 99210_insertar_prods_JJM.txt

echo "Insertando asientos de prueba"
psql -d $DBNAME -U $USUARIO_DB < 99300_datos_de_prueba_contab.sql > 99310_datos_de_prueba_contab.txt

echo "Poniendo secuencias al dia"
./00700_secuencias.sh

echo "Buscando problemas en fks"
psql -d $DBNAME -U $USUARIO_DB < 89900_p_buscar_fks_faltan.sql

echo "Buscando errores"
find . -name "*.txt" -exec grep -l -s -i error {} \;

echo
