delete from autorizadores_rendiciones  ;
delete from autorizadores_requisiciones;
delete from perfiles_programas         ;
delete from usuarios_perfiles          ;
delete from perfiles                   ;
delete from programas                  ;

insert into perfiles values ( 1, 'CONFIGURADOR'                                   , 1, current_timestamp, null, null, null, null);
insert into perfiles values ( 2, 'ADMINISTRADOR DEL CLIENTE'                      , 1, current_timestamp, null, null, null, null);
insert into perfiles values ( 3, 'ADMINISTRADOR EMPRESA'                          , 1, current_timestamp, null, null, null, null);
insert into perfiles values ( 4, 'ADMINISTRADOR DEL CLIENTE Y EMPRESA'            , 1, current_timestamp, null, null, null, null);
insert into perfiles values ( 5, 'GERENTE GENERAL'                                , 1, current_timestamp, null, null, null, null);
insert into perfiles values ( 6, 'SECRETARIA GERENTE GENERAL'                     , 1, current_timestamp, null, null, null, null);
insert into perfiles values ( 7, 'GERENTE DE ADMINISTRACION Y FINANZAS'           , 1, current_timestamp, null, null, null, null);
insert into perfiles values ( 8, 'SECRETARIA GERENTE DE ADMINISTRACION Y FINANZAS', 1, current_timestamp, null, null, null, null);
insert into perfiles values ( 9, 'TESORERO'                                       , 1, current_timestamp, null, null, null, null);
insert into perfiles values (10, 'ASISTENTE 1 TESORERO'                           , 1, current_timestamp, null, null, null, null);
insert into perfiles values (11, 'ASISTENTE 2 TESORERO'                           , 1, current_timestamp, null, null, null, null);
insert into perfiles values (12, 'CAJERO'                                         , 1, current_timestamp, null, null, null, null);
insert into perfiles values (13, 'CONTADOR GENERAL'                               , 1, current_timestamp, null, null, null, null);
insert into perfiles values (14, 'ASISTENTE 1 CONTABILIDAD'                       , 1, current_timestamp, null, null, null, null);
insert into perfiles values (15, 'ASISTENTE 2 CONTABILIDAD'                       , 1, current_timestamp, null, null, null, null);
insert into perfiles values (16, 'JEFE DE COMPRAS'                                , 1, current_timestamp, null, null, null, null);
insert into perfiles values (17, 'AYUDANTE JEFE DE COMPRAS'                       , 1, current_timestamp, null, null, null, null);
insert into perfiles values (18, 'JEFE DE VENTAS'                                 , 1, current_timestamp, null, null, null, null);
insert into perfiles values (19, 'AYUDANTE JEFE DE VENTAS'                        , 1, current_timestamp, null, null, null, null);
insert into perfiles values (20, 'VENDEDOR'                                       , 1, current_timestamp, null, null, null, null);
insert into perfiles values (21, 'USUARIO'                                        , 1, current_timestamp, null, null, null, null);

insert into usuarios_perfiles values (1 , 1 , 1, null, null, 1, 1, current_timestamp, null, null, null, null);
insert into usuarios_perfiles values (2 , 2 , 1, null, null, 1, 1, current_timestamp, null, null, null, null);
insert into usuarios_perfiles values (3 , 3 , 1, null, null, 1, 1, current_timestamp, null, null, null, null);
insert into usuarios_perfiles values (4 , 4 , 1, null, null, 1, 1, current_timestamp, null, null, null, null);
insert into usuarios_perfiles values (5 , 5 , 1, null, null, 1, 1, current_timestamp, null, null, null, null);
insert into usuarios_perfiles values (6 , 6 , 1, null, null, 1, 1, current_timestamp, null, null, null, null);
insert into usuarios_perfiles values (7 , 7 , 1, null, null, 1, 1, current_timestamp, null, null, null, null);
insert into usuarios_perfiles values (8 , 8 , 1, null, null, 1, 1, current_timestamp, null, null, null, null);
insert into usuarios_perfiles values (9 , 9 , 1, null, null, 1, 1, current_timestamp, null, null, null, null);
insert into usuarios_perfiles values (10, 10, 1, null, null, 1, 1, current_timestamp, null, null, null, null);

insert into programas values ( 1000, null , 'Personales'                           , null                              , 'Personales'                                , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 1010,  1000, 'Mantención datos personales'          , 'personas/datos-personales'       , 'Mantención datos personales'               , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 1020,  1000, 'Cambio clave acceso'                  , 'usuarios/cambio_contrasena'      , 'Cambio clave acceso'                       , 2  , 1, current_timestamp, null, null, null, null);

insert into programas values ( 2000, null , 'Adm. sistema 1'                       , null                              , 'Administracion sistema grupo 1'            , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2010,  2000, 'Mantención grupos empresariales'      , 'grupos-empresariales'            , 'Mantención grupos empresariales'           , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2020,  2000, 'Mant. estados grupos empresariales'   , 'estados-grem'                    , 'Mantención estados grupos empresariales'   , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2030,  2000, 'Mant. estados registros'              , 'estados-registros'               , 'Mantención estados registros'              , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2040,  2000, 'Mant. estados civiles'                , 'estados-civiles'                 , 'Mantención estados civiles'                , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2050,  2000, 'Mant. estados solics. servs. hono.'   , 'principales/en-construccion'     , 'Mantención estados solics. servs. hono.'   , 5  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2060,  2000, 'Mant. estados cotizacs. servs. hono.' , 'principales/en-construccion'     , 'Mantención estados cotizacs. servs. hono.' , 6  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2070,  2000, 'Mant. estados órdenes servs. hono.'   , 'principales/en-construccion'     , 'Mantención estados órdenes servs. hono.'   , 7  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2080,  2000, 'Mant. ests. pagos órds. servs. hono.' , 'principales/en-construccion'     , 'Mantención ests. pagos órds. servs. hono.' , 8  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2090,  2000, 'Mant. estados cotizaciones vtas.'     , 'estados-cotizaciones-vtas'       , 'Mantención estados cotizaciones vtas.'     , 9  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2100,  2000, 'Mant. estados notas vtas.'            , 'estados-notas-vtas'              , 'Mantención estados notas vtas.'            , 10 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2110,  2000, 'Mant. impuestos'                      , 'impuestos'                       , 'Mantención impuestos'                      , 11 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2120,  2000, 'Mant. tipos formas pagos'             , 'tipos-formas-pagos'              , 'Mantención tipos formas pagos'             , 12 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2130,  2000, 'Mant. tipos clientes'                 , 'tipos-clientes'                  , 'Mantención tipos clientes'                 , 13 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2140,  2000, 'Mant. tipos cotizaciones vtas.'       , 'tipos-cotizaciones-vtas'         , 'Mantención tipos cotizaciones vtas.'       , 14 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2150,  2000, 'Mant. tipos productos'                , 'tipos-productos'                 , 'Mantención tipos productos'                , 15 , 1, current_timestamp, null, null, null, null);

insert into programas values ( 2200, null , 'Adm. sistema 2'                       , null                              , 'Administracion sistema grupo 2'            , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2210,  2200, 'Mant. tipos productos impuestos'      , 'tipos-productos-impuestos'       , 'Mantención tipos productos impuestos'      , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2220,  2200, 'Mant. tipos servicios'                , 'tipos-servicios'                 , 'Mantención tipos servicios'                , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2230,  2200, 'Mant. unidades territoriales'         , 'unidades-territoriales'          , 'Mantención unidades territoriales'         , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2240,  2200, 'Mant. estados ventas'                 , 'estados-ventas'                  , 'Mantención estados ventas'                 , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2250,  2200, 'Mant. origenes productos'             , 'origenes-productos'              , 'Mantención origenes productos'             , 5  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2260,  2200, 'Mant. tipos doctos. ventas'           , 'tipos-doctos-ventas'             , 'Mantención tipos doctos. ventas'           , 6  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2270,  2200, 'Mant. unidades medidas productos'     , 'unidades-medidas-productos'      , 'Mantención unidades medidas productos'     , 7  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2280,  2200, 'Mant. unidades medidas servicios'     , 'unidades-medidas-servicios'      , 'Mantención unidades medidas servicios'     , 8  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2290,  2200, 'Mant. tipos movimientos bodegas'      , 'tipos-movimientos-bodegas'       , 'Mantención tipos movimientos bodegas'      , 9  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2300,  2200, 'Mant. estados requisiciones'          , 'EstadosRequisiciones'            , 'Mantención estados requisiciones'          , 10 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2310,  2200, 'Mant. tipos requisiciones'            , 'TiposRequisiciones'              , 'Mantención tipos requisiciones'            , 11 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2320,  2200, 'Mant. estados órdenes compras'        , 'EstadosOrdenesCompras'           , 'Mantención estados órdenes compras'        , 12 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2330,  2200, 'Mant. estados detalles OC'            , 'EstadosDetallesOrdenesCompras'   , 'Mantención estados detalles OC'            , 13 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2340,  2200, 'Mant. tipos proveedores'              , 'TiposProveedores'                , 'Mantención tipos proveedores'              , 14 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2350,  2200, 'Mant. perfiles'                       , 'Perfiles'                        , 'Mantención perfiles y sus programas'       , 15 , 1, current_timestamp, null, null, null, null);

insert into programas values ( 2400, null , 'Adm. sistema 3'                       , null                              , 'Administracion sistema grupo 3'            , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2410,  2400, 'Mant. tipos rendiciones gastos'       , 'TiposRendicionesGastos'          , 'Mantención tipos rendiciones gastos'       , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2420,  2400, 'Mant. estados rendiciones gastos'     , 'EstadosRendicionesGastos'        , 'Mantención estados rendiciones gastos'     , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2430,  2400, 'Mant. rubros'                         , 'rubros'                          , 'Mantención rubros'                         , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 2440,  2400, 'Buscador usuarios'                    , 'XXXXX'                           , 'Buscador de usuarios en holdings o emp.'   , 4  , 1, current_timestamp, null, null, null, null);

insert into programas values ( 3000, null , 'Adm. holding'                         , null                              , 'Administracion holding'                    , 5  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 3010,  3000, 'Mant. empresas'                       , 'empresas'                        , 'Mantención empresas'                       , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 3020,  3000, 'Mant. personas'                       , 'personas'                        , 'Mantención personas'                       , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 3030,  3000, 'Mant. usuarios'                       , 'mant-usuarios'                   , 'Mantención usuarios'                       , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 3040,  3000, 'Mant. parámetros'                     , 'parametros'                      , 'Mantención parámetros'                     , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 3050,  3000, 'Mant. plan de cuentas'                , 'principales/en-construccion'     , 'Mantención plan de cuentas'                , 5  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 3060,  3000, 'Mant. tipos documentos legales'       , 'TiposDocumentosLegales'          , 'Mantención tipos documentos legales'       , 6  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 3070,  3000, 'Mant. estados documentos legales'     , 'estados-documentos-legales'      , 'Mantención estados documentos legales'     , 7  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 3080,  3000, 'Mant. clientes'                       , 'clientes'                        , 'Mantención clientes'                       , 8  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 3090,  3000, 'Mant. conceptos rendiciones gastos'   , 'ConceptosRendicionesGastos'      , 'Mantención conceptos rendiciones gastos'   , 9  , 1, current_timestamp, null, null, null, null);

insert into programas values ( 4000, null , 'Adm. empresa 1'                       , null                              , 'Administracion empresa 1'                  , 6  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4010,  4000, 'Mant. gerencias'                      , 'gerencias'                       , 'Mantención gerencias'                      , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4020,  4000, 'Mant. proyectos'                      , 'proyectos'                       , 'Mantención proyectos'                      , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4030,  4000, 'Mant. líneas de negocios'             , 'lineas-negocios'                 , 'Mantención líneas de negocios'             , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4040,  4000, 'Mant. centros costos'                 , 'centros-costos'                  , 'Mantención centros costos'                 , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4050,  4000, 'Mant. tareas'                         , 'tareas'                          , 'Mantención tareas'                         , 5  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4060,  4000, 'Mant. productos'                      , 'productos'                       , 'Mantención productos'                      , 6  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4070,  4000, 'Mant. servicios'                      , 'servicios'                       , 'Mantención servicios'                      , 7  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4080,  4000, 'Mant. listas precios'                 , 'listas-precios'                  , 'Mantención listas precios'                 , 8  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4100,  4000, 'Mant. descuentos'                     , 'descuentos'                      , 'Mantención descuentos'                     , 10 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4110,  4000, 'Bitácoras cambios precios'            , 'bitacoras-cambios-precios'       , 'Bitácoras cambios precios'                 , 11 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4120,  4000, 'Mant. parámetros empresas'            , 'ParametrosEmpresas'              , 'Mantención parámetros empresas'            , 12 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4130,  4000, 'Mant. autorizadores rendiciones'      , 'AutorizadoresRendiciones'        , 'Mantención autorizadores rendiciones'      , 13 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4140,  4000, 'Mant. autorizadores requisiciones'    , 'AutorizadoresRequisiciones'      , 'Mantención autorizadores requisiciones'    , 14 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4150,  4000, 'Mant. fondos a rendir'                , 'FondosARendir'                   , 'Mantención fondos a rendir'                , 15 , 1, current_timestamp, null, null, null, null);

insert into programas values ( 4500, null , 'Adm. empresa 2'                       , null                              , 'Administracion empresa 2'                  , 7  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 4510,  4500, 'Mant. proveedores'                    , 'proveedores'                     , 'Mantención proveedores'                    , 1  , 1, current_timestamp, null, null, null, null);

insert into programas values ( 5000, null , 'Legales'                              , null                              , 'Legales'                                   , 8  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 5010,  5000, 'Documentos legales'                   , 'DocumentosLegales'               , 'Documentos legales'                        , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 5020,  5000, 'Gráfica legales'                      , 'DocumentosLegales/estadisticas'  , 'Gráfica legales'                           , 2  , 1, current_timestamp, null, null, null, null);

insert into programas values ( 6000, null , 'Honorarios'                           , null                              , 'Honorarios'                                , 9  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 6010,  6000, 'Honorarios 1'                         , 'principales/en-construccion'     , 'Honorarios 1'                              , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 6020,  6000, 'Honorarios 2'                         , 'principales/en-construccion'     , 'Honorarios 2'                              , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 6030,  6000, 'Honorarios 3'                         , 'principales/en-construccion'     , 'Honorarios 3'                              , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 6040,  6000, 'Honorarios 4'                         , 'principales/en-construccion'     , 'Honorarios 4'                              , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 6050,  6000, 'Honorarios 5'                         , 'principales/en-construccion'     , 'Honorarios 5'                              , 5  , 1, current_timestamp, null, null, null, null);

insert into programas values ( 7000, null , 'Rendiciones'                          , null                              , 'Rendiciones'                               , 10 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 7010,  7000, 'Fondos a rendir'                      , 'principales/en-construccion'     , 'Fondos a rendir'                           , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 7020,  7000, 'Ingreso rendiciones'                  , 'principales/en-construccion'     , 'Ingreso rendiciones'                       , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 7030,  7000, 'Aceptación/rechazo rendiciones'       , 'principales/en-construccion'     , 'Aceptación/rechazo rendiciones'            , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 7040,  7000, 'Aprobac./rech. rends. dpto. contab.'  , 'principales/en-construccion'     , 'Aprobac./rech. rends. dpto. contab.'       , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 7050,  7000, 'Contabilización rendiciones'          , 'principales/en-construccion'     , 'Contabilización rendiciones'               , 5  , 1, current_timestamp, null, null, null, null);

insert into programas values ( 8000, null , 'Compras'                              , null                              , 'Compras'                                   , 11 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 8010,  8000, 'Registro requisiciones'               , 'Requisiciones'                   , 'Registro requisiciones'                    , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 8020,  8000, 'Aceptación/rechazo requisiciones'     , 'RequisicionesAutorizador'        , 'Aceptación/rechazo requisiciones'          , 2  , 1, current_timestamp, null, null, null, null);
--sert into programas values ( 8030,  8000, 'Recepción requisiciones'              , 'principales/en-construccion'     , 'Recepción requisiciones'                   , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 8040,  8000, 'Aprobac./rech. reqs. dpto. compras'   , 'RequisicionesCompras'            , 'Aprobac./rech. reqs. dpto. compras'        , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 8050,  8000, 'Órdenes de compras'                   , 'OrdenesCompras'                  , 'Órdenes de compras'                        , 5  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 8060,  8000, 'Recepciones compras/servicios'        , 'RecepcionesCompras'              , 'Recepciones compras/servicios'             , 6  , 1, current_timestamp, null, null, null, null);

insert into programas values ( 9000, null , 'Ventas'                               , null                              , 'Ventas'                                    , 12 , 1, current_timestamp, null, null, null, null);
insert into programas values ( 9010,  9000, 'Cotizaciones ventas'                  , 'CotizacionesVentas'              , 'Cotizaciones ventas'                       , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 9020,  9000, 'Aprobación de cotizaciones'           , 'CotizacionesVentas/selCotizs'    , 'Aprobación de cotizaciones'                , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 9030,  9000, 'Notas ventas'                         , 'NotasVentas'                     , 'Notas ventas'                              , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values ( 9040,  9000, 'Ventas'                               , 'Ventas'                          , 'Ventas'                                    , 4  , 1, current_timestamp, null, null, null, null);

insert into programas values (10000, null , 'Contabilidad'                         , null                              , 'Contabilidad'                              , 13 , 1, current_timestamp, null, null, null, null);
insert into programas values (10010, 10000, 'Mantención cuentas contables'         , 'CuentasContables'                , 'Mantención cuentas contables'              , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values (10020, 10000, 'Mantención asientos contables'        , 'AsientosContables'               , 'Mantención asientos contables'             , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values (10030, 10000, 'Autorización asientos contables'      , 'AutorizacionAsientosContables'   , 'Autorización asientos contables'           , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values (10040, 10000, 'Reportes contables'                   , 'ReportesContables'               , 'Acceso a diversos reportes contables'      , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values (10050, 10000, 'Contabilización automática de compras', 'principales/en-construccion'     , 'Contabilización automática de compras'     , 5  , 1, current_timestamp, null, null, null, null);
insert into programas values (10060, 10000, 'Contabilización automática de ventas' , 'principales/en-construccion'     , 'Contabilización automática de ventas'      , 6  , 1, current_timestamp, null, null, null, null);
insert into programas values (10070, 10000, 'Mant. parámetros cont. aut. ventas'   , 'principales/en-construccion'     , 'Mant. parámetros cont. aut. ventas'        , 7  , 1, current_timestamp, null, null, null, null);
insert into programas values (10080, 10000, 'Mant. parámetros cont. aut. compras'  , 'principales/en-construccion'     , 'Mant. parámetros cont. aut. compras'       , 8  , 1, current_timestamp, null, null, null, null);

insert into programas values (11000, null , 'Existencias'                          , null                              , 'Existencias'                               , 14 , 1, current_timestamp, null, null, null, null);
insert into programas values (11010, 11000, 'Mantención bodegas'                   , 'bodegas'                         , 'Mantención bodegas'                        , 1  , 1, current_timestamp, null, null, null, null);
insert into programas values (11020, 11000, 'Mantención familias productos'        , 'familias-productos'              , 'Mantención familias productos'             , 2  , 1, current_timestamp, null, null, null, null);
insert into programas values (11030, 11000, 'Mantención sub familias productos'    , 'sub-familias-productos'          , 'Mantención sub familias productos'         , 3  , 1, current_timestamp, null, null, null, null);
insert into programas values (11040, 11000, 'Productos por bodega'                 , 'bodegas-productos'               , 'Productos por bodega'                      , 4  , 1, current_timestamp, null, null, null, null);
insert into programas values (11050, 11000, 'Consulta kardex por producto'         , 'movimientos-bodegas'             , 'Consulta kardex por producto'              , 5  , 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2050, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2060, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2070, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2080, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2090, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2100, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2110, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2120, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2130, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2140, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2150, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2200, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2210, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2220, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2230, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2240, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2250, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2260, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2270, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2280, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2290, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2300, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2310, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2320, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2330, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2340, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2350, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2400, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2410, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2420, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2430, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 1 ,  2440, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3050, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3060, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3070, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3080, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  3090, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 2 ,  8010, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4050, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4060, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4070, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4080, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4100, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4110, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4120, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4130, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4140, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4150, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4500, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  4510, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 3 ,  8010, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  3000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  3010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  3020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  3030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  3040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  3060, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  3070, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  3080, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  3090, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4050, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4060, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4070, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4080, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4100, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4110, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4120, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4130, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4140, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4150, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4500, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  4510, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 ,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 , 11000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 , 11010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 , 11020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 , 11030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 , 11040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 4 , 11050, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 5 ,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 5 ,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 5 ,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 5 ,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 5 ,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 5 ,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 5 ,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 5 ,  8020, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 6 ,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 6 ,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 6 ,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 6 ,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 6 ,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 6 ,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 6 ,  8010, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 7 ,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 7 ,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 7 ,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 7 ,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 7 ,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 7 ,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 7 ,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 7 ,  8020, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 8 ,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 8 ,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 8 ,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 8 ,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 8 ,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 8 ,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 8 ,  8010, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 9 ,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 9 ,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 9 ,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 9 ,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 9 ,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 9 ,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 9 ,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 9 ,  8020, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 10,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 10,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 10,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 10,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 10,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 10,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 10,  8010, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 11,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 11,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 11,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 11,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 11,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 11,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 11,  8010, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 12,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 12,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 12,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 12,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 12,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 12,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 12,  8010, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 13,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13,  8020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13, 10000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13, 10010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13, 10020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13, 10030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13, 10040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13, 10050, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13, 10060, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13, 10070, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 13, 10080, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 14,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14, 10000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14, 10020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14, 10030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14, 10040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14, 10050, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 14, 10060, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 15,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15, 10000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15, 10020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15, 10030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15, 10040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15, 10050, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 15, 10060, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 16,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  8020, 1, current_timestamp, null, null, null, null);
--sert into perfiles_programas values (nextval('pepr_seq'), 16,  8030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  8040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  8050, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 16,  8060, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 17,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 17,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 17,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 17,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 17,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 17,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 17,  8010, 1, current_timestamp, null, null, null, null);
--sert into perfiles_programas values (nextval('pepr_seq'), 17,  8030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 17,  8040, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 17,  8050, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 17,  8060, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 18,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  8020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  9000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  9010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  9020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  9030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 18,  9040, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 19,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  9000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  9010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  9020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  9030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 19,  9040, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 20,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  3090, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  3000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  8010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  9000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  9010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  9020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  9030, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 20,  9040, 1, current_timestamp, null, null, null, null);

insert into perfiles_programas values (nextval('pepr_seq'), 21,  1000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 21,  1010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 21,  1020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 21,  5000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 21,  5010, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 21,  5020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 21,  7000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 21,  7020, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 21,  8000, 1, current_timestamp, null, null, null, null);
insert into perfiles_programas values (nextval('pepr_seq'), 21,  8010, 1, current_timestamp, null, null, null, null);

alter table autorizadores_requisiciones  add constraint aure_fk1_perf foreign key (idperfautorizador) references perfiles (id);
alter table autorizadores_requisiciones  add constraint aure_fk2_perf foreign key (idperfautorizado)  references perfiles (id);

alter table autorizadores_rendiciones    add constraint aurn_fk1_perf foreign key (idperfautorizador) references perfiles (id);
alter table autorizadores_rendiciones    add constraint aurn_fk2_perf foreign key (idperfautorizado)  references perfiles (id);

\q
