create or replace function f_crear_datos_holding() returns trigger as
$body$
declare
  aux numeric;
begin

/*
insert into enlaces_contables values (nextval('enco_seq'), 1, 'valor neto venta'      , 'ventas', 'exento+afecto+montodescuen
insert into enlaces_contables values (nextval('enco_seq'), 1, 'impuestos obligatorios', 'ventas', 'impuestosobligats'
insert into enlaces_contables values (nextval('enco_seq'), 1, 'impuestos específicos' , 'ventas', 'impuestosespecifs'
insert into enlaces_contables values (nextval('enco_seq'), 1, 'total'                 , 'ventas', 'total'
*/

  insert into parametros values (nextval('para_seq'), new.id, 'LARGOMINCLAVE'   , 'LARGO MÍNIMO CLAVES USUARIOS'                          , 'LARGO MINIMO EXIGIDO PARA LAS CLAVES DE LOS USUARIOS'                                                            , '5'           , 1, current_timestamp, null, null, null, null);
  insert into parametros values (nextval('para_seq'), new.id, 'NROSEGMSCUCO'    , 'NUMERO DE SEGMENTOS EN EL PLAN DE CUENTAS'             , 'NUMERO DE SEGMENTOS QUE COMPONEN EL PLAN DE CUENTAS DE ESTE HOLDING'                                             , '4'           , 1, current_timestamp, null, null, null, null);
  insert into parametros values (nextval('para_seq'), new.id, 'UMVALNOTVE'      , 'UNIDAD DE MEDIDA VALIDEZ NOTA VENTA'                   , 'H = HORAS; D = DÍAS'                                                                                             , 'D'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'CADUCNV'         , 'CADUCIDAD NOTAS DE VENTA'                              , 'TIEMPO TRAS EL CUAL CADUCA UNA NOTA DE VENTA (1 DÍA, 2 HORAS, ETC.)'                                             , '1'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'VALIDEZCOTI'     , 'DEFAULT DÍAS VALIDEZ COTIZACIÓN'                       , 'DÍAS DE VALIDEZ POR DEFECTO DE UNA COTIZACIÓN'                                                                   , '5'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'LARGOSEGM1'      , 'LARGO DEL SEGMENTO 1'                                  , 'LARGO DEL SEGMENTO 1 DE LAS CUENTAS CONTABLES DE ESTE HOLDING'                                                   , '1'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'LARGOSEGM2'      , 'LARGO DEL SEGMENTO 2'                                  , 'LARGO DEL SEGMENTO 2 DE LAS CUENTAS CONTABLES DE ESTE HOLDING'                                                   , '2'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'LARGOSEGM3'      , 'LARGO DEL SEGMENTO 3'                                  , 'LARGO DEL SEGMENTO 3 DE LAS CUENTAS CONTABLES DE ESTE HOLDING'                                                   , '2'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'LARGOSEGM4'      , 'LARGO DEL SEGMENTO 4'                                  , 'LARGO DEL SEGMENTO 4 DE LAS CUENTAS CONTABLES DE ESTE HOLDING'                                                   , '4'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'LARGOSEGM5'      , 'LARGO DEL SEGMENTO 5'                                  , 'LARGO DEL SEGMENTO 5 DE LAS CUENTAS CONTABLES DE ESTE HOLDING'                                                   , '0'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'LARGOSEGM6'      , 'LARGO DEL SEGMENTO 6'                                  , 'LARGO DEL SEGMENTO 6 DE LAS CUENTAS CONTABLES DE ESTE HOLDING'                                                   , '0'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'LARGOSEGM7'      , 'LARGO DEL SEGMENTO 7'                                  , 'LARGO DEL SEGMENTO 7 DE LAS CUENTAS CONTABLES DE ESTE HOLDING'                                                   , '0'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'LARGOSEGM8'      , 'LARGO DEL SEGMENTO 8'                                  , 'LARGO DEL SEGMENTO 8 DE LAS CUENTAS CONTABLES DE ESTE HOLDING'                                                   , '0'           , 1, current_timestamp, null, null, null, null);     
  insert into parametros values (nextval('para_seq'), new.id, 'SEPNIVELES'      , 'SEPARADOR NIVELES'                                     , 'CARACTER SEPARADOR DE LOS NIVELES DEL PLAN DE CUENTAS'                                                           , '.'           , 1, current_timestamp, null, null, null, null);
  insert into parametros values (nextval('para_seq'), new.id, 'FORMATOCTAS'     , 'FORMATO CUENTAS CONTABLES'                             , 'FORMATO DE DESPLIEGUE DE LAS CUENTAS CONTABLES'                                                                  , '9.99.99.9999', 1, current_timestamp, null, null, null, null);
  insert into parametros values (nextval('para_seq'), new.id, 'GERE_OBLIGATORIO', 'GERENCIA OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE?'     , 'EL CAMPO IDGERE ES OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE CUANDO LA CUENTA SEA DE TIPO INGRESO (3) O EGRESO (4)', 'N'           , 1, current_timestamp, null, null, null, null);
  insert into parametros values (nextval('para_seq'), new.id, 'PROY_OBLIGATORIO', 'PROYECTO OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE?'     , 'EL CAMPO IDPROY ES OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE CUANDO LA CUENTA SEA DE TIPO INGRESO (3) O EGRESO (4)', 'N'           , 1, current_timestamp, null, null, null, null);
  insert into parametros values (nextval('para_seq'), new.id, 'LINE_OBLIGATORIO', 'LINEA NEGOCIO OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE?', 'EL CAMPO IDLINE ES OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE CUANDO LA CUENTA SEA DE TIPO INGRESO (3) O EGRESO (4)', 'N'           , 1, current_timestamp, null, null, null, null);
  insert into parametros values (nextval('para_seq'), new.id, 'CECO_OBLIGATORIO', 'CENTRO COSTO OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE?' , 'EL CAMPO IDCECO ES OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE CUANDO LA CUENTA SEA DE TIPO INGRESO (3) O EGRESO (4)', 'S'           , 1, current_timestamp, null, null, null, null);
  insert into parametros values (nextval('para_seq'), new.id, 'TARE_OBLIGATORIO', 'TAREA OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE?'        , 'EL CAMPO IDTARE ES OBLIGATORIO EN DETALLE_ASIENTO_CONTABLE CUANDO LA CUENTA SEA DE TIPO INGRESO (3) O EGRESO (4)', 'N'           , 1, current_timestamp, null, null, null, null);

  insert into tipos_documentos_legales values (nextval('tidl_seq'), new.id, 'CONSTITUCIÓN DE SOCIEDAD', 'CONST. SOC.', '#FF0000', 1, current_timestamp, null, null, null, null);
  insert into tipos_documentos_legales values (nextval('tidl_seq'), new.id, 'ACTA DE DIRECTORIO'      , 'ACTA DIR.'  , '#00FF00', 1, current_timestamp, null, null, null, null);
  insert into tipos_documentos_legales values (nextval('tidl_seq'), new.id, 'SESIÓN DE DIRECTORIO'    , 'SES. DIR.'  , '#0000FF', 1, current_timestamp, null, null, null, null);
  insert into tipos_documentos_legales values (nextval('tidl_seq'), new.id, 'CONTRATO DE ARRIENDO'    , 'CONT. ARR.' , '#FFFFFF', 1, current_timestamp, null, null, null, null);

  insert into estados_documentos_legales values (nextval('esdl_seq'), new.id, 'VÁLIDO'  , 1, current_timestamp, null, null, null, null);
  insert into estados_documentos_legales values (nextval('esdl_seq'), new.id, 'INVÁLIDO', 1, current_timestamp, null, null, null, null);
  insert into estados_documentos_legales values (nextval('esdl_seq'), new.id, 'CADUCO'  , 1, current_timestamp, null, null, null, null);

  select nextval('cuco_seq')
  into   aux
  ;

  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '00', '00', '0000', null, null, null, null, 'ACTIVOS'                                                          , 1, 'S', '1.00.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '00', '00', '0000', null, null, null, null, 'PASIVOS'                                                          , 1, 'S', '2.00.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '00', '00', '0000', null, null, null, null, 'INGRESOS'                                                         , 1, 'S', '3.00.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '00', '00', '0000', null, null, null, null, 'EGRESOS'                                                          , 1, 'S', '4.00.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '5', '00', '00', '0000', null, null, null, null, 'CUENTAS DE ORDEN Y TRASPASOS'                                     , 1, 'S', '5.00.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '00', '0000', null, null, null, null, 'ACTIVOS CORRIENTES'                                               , 1, 'S', '1.01.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '00', '0000', null, null, null, null, 'ACTIVOS NO CORRIENTES'                                            , 1, 'S', '1.02.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '00', '0000', null, null, null, null, 'PASIVOS CORRIENTES'                                               , 1, 'S', '2.01.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '02', '00', '0000', null, null, null, null, 'PASIVOS NO CORRIENTES'                                            , 1, 'S', '2.02.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '03', '00', '0000', null, null, null, null, 'PATRIMONIO'                                                       , 1, 'S', '2.03.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '01', '00', '0000', null, null, null, null, 'INGRESOS'                                                         , 1, 'S', '3.01.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '02', '00', '0000', null, null, null, null, 'OTROS INGRESOS'                                                   , 1, 'S', '3.02.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '00', '0000', null, null, null, null, 'COSTO DE VENTA'                                                   , 1, 'S', '4.01.00.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0000', null, null, null, null, 'EFECTIVO Y EQUIVALENTE AL EFECTIVO'                               , 1, 'S', '1.01.01.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '02', '0000', null, null, null, null, 'OTROS ACTIVOS FINANCIEROS'                                        , 1, 'S', '1.01.02.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0000', null, null, null, null, 'OTROS ACTIVOS NO FINANCIEROS'                                     , 1, 'S', '1.01.03.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '04', '0000', null, null, null, null, 'DEUDORES COMERCIALES Y OTRAS CUENTAS POR COBRAR'                  , 1, 'S', '1.01.04.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '05', '0000', null, null, null, null, 'CUENTAS POR COBRAR A ENTIDADES RELACIONADAS'                      , 1, 'S', '1.01.05.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '06', '0000', null, null, null, null, 'INVENTARIOS'                                                      , 1, 'S', '1.01.06.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '07', '0000', null, null, null, null, 'ACTIVOS BIOLOGICOS'                                               , 1, 'S', '1.01.07.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '08', '0000', null, null, null, null, 'ACTIVOS POR IMPUESTOS'                                            , 1, 'S', '1.01.08.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '09', '0000', null, null, null, null, 'ACTIVOS MANTENIDOS PARA LA VENTA'                                 , 1, 'S', '1.01.09.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '10', '0000', null, null, null, null, 'ACTIVOS MANTENIDOS PARA DISTRIBUIR A PROPIETARIOS'                , 1, 'S', '1.01.10.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '11', '0000', null, null, null, null, 'ACTIVOS MANTENIDOS PARA LA VENTA O A DISTRIBUIR A LOS PROPIETARIO', 1, 'S', '1.01.11.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '01', '0000', null, null, null, null, 'DERECHOS POR COBRAR'                                              , 1, 'S', '1.02.01.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '02', '0000', null, null, null, null, 'PROPIEDADES DE INVERSION'                                         , 1, 'S', '1.02.02.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '03', '0000', null, null, null, null, 'ACTIVOS INTANGIBLES DISTINTO A LA PLUSVALIA'                      , 1, 'S', '1.02.03.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '04', '0000', null, null, null, null, 'PLUSVALIA'                                                        , 1, 'S', '1.02.04.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '05', '0000', null, null, null, null, 'PROPIEDADES, PLANTAS Y EQUIPOS'                                   , 1, 'S', '1.02.05.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '06', '0000', null, null, null, null, 'INVERSIONES POR METODO DE PARTICIPACION'                          , 1, 'S', '1.02.06.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '07', '0000', null, null, null, null, 'ACTIVOS POR IMPUESTO DIFERIDO'                                    , 1, 'S', '1.02.07.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '01', '0000', null, null, null, null, 'OTROS PASIVOS FINANCIEROS'                                        , 1, 'S', '2.01.01.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '02', '0000', null, null, null, null, 'CUENTAS COMERCIALES Y OTRAS CUENTAS POR PAGAR'                    , 1, 'S', '2.01.02.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '03', '0000', null, null, null, null, 'CUENTAS POR PAGAR A ENTIDADES RELACIONADAS'                       , 1, 'S', '2.01.03.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '04', '0000', null, null, null, null, 'OTRAS PROVISIONES'                                                , 1, 'S', '2.01.04.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '05', '0000', null, null, null, null, 'PASIVOS POR IMPUESTOS'                                            , 1, 'S', '2.01.05.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '06', '0000', null, null, null, null, 'PROVISIONES POR BENEFICIOS A EMPLEADOS'                           , 1, 'S', '2.01.06.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '07', '0000', null, null, null, null, 'OTROS PASIVOS NO FINANCIEROS'                                     , 1, 'S', '2.01.07.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '08', '0000', null, null, null, null, 'PASIVOS CLASIFICADOS COMO MANTENIDOS PARA LA VENTA'               , 1, 'S', '2.01.08.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '02', '01', '0000', null, null, null, null, 'OTRAS CUENTAS POR PAGAR'                                          , 1, 'S', '2.02.01.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '02', '02', '0000', null, null, null, null, 'PASIVOS POR IMPUESTOS DIFERIDOS'                                  , 1, 'S', '2.02.02.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '02', '03', '0000', null, null, null, null, 'PROVISIONES POR BENEFICIOS A LOS EMPLEADOS'                       , 1, 'S', '2.02.03.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '03', '01', '0000', null, null, null, null, 'CAPITAL EMITIDO'                                                  , 1, 'S', '2.03.01.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '03', '02', '0000', null, null, null, null, 'GANANCIAS (PERDIDAS) ACUMULADAS'                                  , 1, 'S', '2.03.02.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '03', '03', '0000', null, null, null, null, 'PRIMAS DE EMISION'                                                , 1, 'S', '2.03.03.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '03', '04', '0000', null, null, null, null, 'ACCIONES PROPIAS EN CARTERA'                                      , 1, 'S', '2.03.04.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '03', '05', '0000', null, null, null, null, 'OTRAS PARTICIPACIONES EN EL PATRIMONIO'                           , 1, 'S', '2.03.05.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '03', '06', '0000', null, null, null, null, 'OTRAS RESERVAS'                                                   , 1, 'S', '2.03.06.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '03', '07', '0000', null, null, null, null, 'PATRIMONIO ATRIBUIBLE A PROPIETARIOS DE LA CONTROLADORA'          , 1, 'S', '2.03.07.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '03', '08', '0000', null, null, null, null, 'PARTICIPACIONES NO CONTROLADORAS'                                 , 1, 'S', '2.03.08.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '01', '01', '0000', null, null, null, null, 'INGRESOS DE ACTIVIDADES ORDINARIAS'                               , 1, 'S', '3.01.01.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '02', '01', '0000', null, null, null, null, 'OTRAS GANANCIAS'                                                  , 1, 'S', '3.02.01.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '02', '02', '0000', null, null, null, null, 'INGRESOS FINANCIEROS'                                             , 1, 'S', '3.02.02.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '01', '0000', null, null, null, null, 'OTROS COSTOS DE EXPLOTACION'                                      , 1, 'S', '4.01.01.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0000', null, null, null, null, 'GASTOS DE ADMINISTRACION Y VENTA'                                 , 1, 'S', '4.01.02.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '03', '0000', null, null, null, null, 'OTROS GASTOS'                                                     , 1, 'S', '4.01.03.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '04', '0000', null, null, null, null, 'COSTOS FINANCIEROS'                                               , 1, 'S', '4.01.04.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '05', '0000', null, null, null, null, 'PARTICIPACION EN RESULTADO POR INVERSIONES'                       , 1, 'S', '4.01.05.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '06', '0000', null, null, null, null, 'DIFERENCIA DE CAMBIO'                                             , 1, 'S', '4.01.06.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '07', '0000', null, null, null, null, 'RESULTADO POR UNIDADES DE REAJUSTES'                              , 1, 'S', '4.01.07.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '08', '0000', null, null, null, null, 'GASTOS POR IMPUESTO A LA RENTA'                                   , 1, 'S', '4.01.08.0000', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0001', null, null, null, null, 'CAJA'                                                             , 1, 'S', '1.01.01.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0002', null, null, null, null, 'FONDO FIJO'                                                       , 1, 'S', '1.01.01.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0003', null, null, null, null, 'BANCO SANTANDER'                                                  , 1, 'S', '1.01.01.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0004', null, null, null, null, 'BANCO DE CHILE'                                                   , 1, 'S', '1.01.01.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0005', null, null, null, null, 'BANCO BBVA'                                                       , 1, 'S', '1.01.01.0005', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0006', null, null, null, null, 'BANCO BCI'                                                        , 1, 'S', '1.01.01.0006', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0007', null, null, null, null, 'BANCO ITAU'                                                       , 1, 'S', '1.01.01.0007', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0008', null, null, null, null, 'BANCO SECURITY'                                                   , 1, 'S', '1.01.01.0008', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0009', null, null, null, null, 'BANCO SANTANDER DOLAR'                                            , 1, 'S', '1.01.01.0009', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0010', null, null, null, null, 'BANCO DE CHILE DOLAR'                                             , 1, 'S', '1.01.01.0010', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0011', null, null, null, null, 'BANCO BBVA DOLAR'                                                 , 1, 'S', '1.01.01.0011', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0012', null, null, null, null, 'BANCO BCI DOLAR'                                                  , 1, 'S', '1.01.01.0012', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0013', null, null, null, null, 'BANCO ITAU DOLAR'                                                 , 1, 'S', '1.01.01.0013', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '01', '0014', null, null, null, null, 'BANCO SECURITY DOLAR'                                             , 1, 'S', '1.01.01.0014', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '02', '0001', null, null, null, null, 'DEPOSITOS A PLAZO'                                                , 1, 'S', '1.01.02.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '02', '0002', null, null, null, null, 'FONDOS MUTUOS'                                                    , 1, 'S', '1.01.02.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '02', '0003', null, null, null, null, 'PACTOS RETROVENTA'                                                , 1, 'S', '1.01.02.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0001', null, null, null, null, 'CLIENTES NACIONALES'                                              , 1, 'S', '1.01.03.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0002', null, null, null, null, 'CLIENTES EXTRANJEROS'                                             , 1, 'S', '1.01.03.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0003', null, null, null, null, 'CHEQUES EN CARTERA'                                               , 1, 'S', '1.01.03.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0004', null, null, null, null, 'TARJETA DE DEBITO'                                                , 1, 'S', '1.01.03.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0005', null, null, null, null, 'TARJETA DE CREDITO'                                               , 1, 'S', '1.01.03.0005', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0006', null, null, null, null, 'CHEQUES PROTESTADOS'                                              , 1, 'S', '1.01.03.0006', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0007', null, null, null, null, 'DOCUMENTOS PROTESTADOS'                                           , 1, 'S', '1.01.03.0007', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0008', null, null, null, null, 'ESTIMACION DEUDORES INCOBRABLES'                                  , 1, 'S', '1.01.03.0008', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0009', null, null, null, null, 'FONDOS POR RENDIR'                                                , 1, 'S', '1.01.03.0009', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0010', null, null, null, null, 'PRESTAMOS AL PERSONAL'                                            , 1, 'S', '1.01.03.0010', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0011', null, null, null, null, 'ANTICIPO DE SUELDO'                                               , 1, 'S', '1.01.03.0011', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0012', null, null, null, null, 'ANTICIPO DE HONORARIOS'                                           , 1, 'S', '1.01.03.0012', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '03', '0013', null, null, null, null, 'ANTICIPO A PROVEEDORES'                                           , 1, 'S', '1.01.03.0013', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '04', '0001', null, null, null, null, 'CUENTAS POR COBRAR EMPRESA RELACIONADA NACIONAL'                  , 1, 'S', '1.01.04.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '04', '0002', null, null, null, null, 'CUENTAS POR COBRAR EMPRESA RELACIONADA EXTRANJERA'                , 1, 'S', '1.01.04.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '05', '0001', null, null, null, null, 'EXISTENCIA EN TRANSITO'                                           , 1, 'S', '1.01.05.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '05', '0002', null, null, null, null, 'EXISTENCIAS EN PROCESO'                                           , 1, 'S', '1.01.05.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '05', '0003', null, null, null, null, 'EXISTENCIAS'                                                      , 1, 'S', '1.01.05.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '06', '0001', null, null, null, null, 'PAGOS PROVISIONALES MENSUALES'                                    , 1, 'S', '1.01.06.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '06', '0002', null, null, null, null, 'IVA CREDITO FISCAL'                                               , 1, 'S', '1.01.06.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '06', '0003', null, null, null, null, 'OTROS IMPUESTOS POR RECUPERAR'                                    , 1, 'S', '1.01.06.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '01', '07', '0001', null, null, null, null, 'ACTIVOS DISPONIBLES MANTENIDOS PARA LA VENTA'                     , 1, 'S', '1.01.07.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '01', '0001', null, null, null, null, 'SEGUROS PAGADOS POR ANTICIPADO'                                   , 1, 'S', '1.02.01.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '01', '0002', null, null, null, null, 'ARRIENDOS PAGADOS POR ANTICIPADO'                                 , 1, 'S', '1.02.01.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '01', '0003', null, null, null, null, 'OTROS GASTOS PAGADOS POR ANTICIPADO'                              , 1, 'S', '1.02.01.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '01', '0004', null, null, null, null, 'GARANTIAS'                                                        , 1, 'S', '1.02.01.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '01', '0005', null, null, null, null, 'INTERESES DIFERIDOS'                                              , 1, 'S', '1.02.01.0005', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '02', '0001', null, null, null, null, 'TERRENOS'                                                         , 1, 'S', '1.02.02.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '02', '0002', null, null, null, null, 'CONSTRUCCIONES E INTALACIONES'                                    , 1, 'S', '1.02.02.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '02', '0003', null, null, null, null, 'MUEBLES E UTILES'                                                 , 1, 'S', '1.02.02.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '02', '0004', null, null, null, null, 'VEHICULOS'                                                        , 1, 'S', '1.02.02.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '02', '0005', null, null, null, null, 'EQUIPOS COMPUTACIONALES'                                          , 1, 'S', '1.02.02.0005', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '02', '0006', null, null, null, null, 'ACTIVOS EN LEASING'                                               , 1, 'S', '1.02.02.0006', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '02', '0007', null, null, null, null, 'PROGRAMAS Y SOFTWARES'                                            , 1, 'S', '1.02.02.0007', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '1', '02', '02', '0008', null, null, null, null, 'DEPRECIACION ACUMULADA'                                           , 1, 'S', '1.02.02.0008', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '01', '0001', null, null, null, null, 'OBLIGACIONES CON BANCOS'                                          , 1, 'S', '2.01.01.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '01', '0002', null, null, null, null, 'LINEAS DE CREDITO'                                                , 1, 'S', '2.01.01.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '01', '0003', null, null, null, null, 'OBLIGACIONES CON LEASING'                                         , 1, 'S', '2.01.01.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '02', '0001', null, null, null, null, 'PROVEEDORES NACIONALES'                                           , 1, 'S', '2.01.02.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '02', '0002', null, null, null, null, 'PROVEEDORES EXTRANJEROS'                                          , 1, 'S', '2.01.02.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '02', '0003', null, null, null, null, 'CHEQUES POR PAGAR'                                                , 1, 'S', '2.01.02.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '02', '0004', null, null, null, null, 'HONORARIOS POR PAGAR'                                             , 1, 'S', '2.01.02.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '02', '0005', null, null, null, null, 'ANTICIPOS DE CLIENTES'                                            , 1, 'S', '2.01.02.0005', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '03', '0001', null, null, null, null, 'CUENTAS POR PAGAR ENTIDAD RELACIONADA NACIONAL'                   , 1, 'S', '2.01.03.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '03', '0002', null, null, null, null, 'CUENTAS POR PAGAR ENTIDAD RELACIONADA EXTRANJERA'                 , 1, 'S', '2.01.03.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '04', '0001', null, null, null, null, 'PROVISIONES POR PAGAR'                                            , 1, 'S', '2.01.04.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '04', '0002', null, null, null, null, 'PROVISION DE VACACIONES'                                          , 1, 'S', '2.01.04.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '04', '0003', null, null, null, null, 'PROVISIONES VARIAS'                                               , 1, 'S', '2.01.04.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '05', '0001', null, null, null, null, 'IVA DEBITO FISCAL'                                                , 1, 'S', '2.01.05.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '05', '0002', null, null, null, null, 'IVA POR PAGAR'                                                    , 1, 'S', '2.01.05.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '05', '0003', null, null, null, null, 'RETENCION 1RA CATEGORIA'                                          , 1, 'S', '2.01.05.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '05', '0004', null, null, null, null, 'RETENCION 2DA CATEGORIA'                                          , 1, 'S', '2.01.05.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '05', '0005', null, null, null, null, 'PPM POR PAGAR'                                                    , 1, 'S', '2.01.05.0005', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '05', '0006', null, null, null, null, 'PROVISION IMPUESTO A LA RENTA'                                    , 1, 'S', '2.01.05.0006', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '06', '0001', null, null, null, null, 'IMPUESTOS POR PAGAR'                                              , 1, 'S', '2.01.06.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '06', '0002', null, null, null, null, 'OTROS IMPUESTOS POR PAGAR'                                        , 1, 'S', '2.01.06.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '01', '06', '0003', null, null, null, null, 'DESCUENTOS APLICADOS'                                             , 1, 'S', '2.01.06.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '02', '01', '0001', null, null, null, null, 'CAPITAL'                                                          , 1, 'S', '2.02.01.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '2', '02', '02', '0001', null, null, null, null, 'RESULTADO ACUMULADO'                                              , 1, 'S', '2.02.02.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '01', '01', '0001', null, null, null, null, 'VENTA DE GRUAS'                                                   , 1, 'S', '3.01.01.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '01', '01', '0002', null, null, null, null, 'VENTA DE ACCESORIAS DE GRUAS'                                     , 1, 'S', '3.01.01.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '01', '01', '0003', null, null, null, null, 'VENTA DE PLATAFORMAS'                                             , 1, 'S', '3.01.01.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '01', '01', '0004', null, null, null, null, 'VENTA DE REPUESTOS'                                               , 1, 'S', '3.01.01.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '01', '01', '0005', null, null, null, null, 'VENTA DE SERVICIO TECNICO'                                        , 1, 'S', '3.01.01.0005', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '01', '01', '0006', null, null, null, null, 'VENTA DE LEASING'                                                 , 1, 'S', '3.01.01.0006', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '3', '01', '01', '0007', null, null, null, null, 'ARRIENDOS'                                                        , 1, 'S', '3.01.01.0007', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '01', '0001', null, null, null, null, 'COSTO DE GRUAS'                                                   , 1, 'S', '4.01.01.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '01', '0002', null, null, null, null, 'COSTO DE ACCESORIAS DE GRUAS'                                     , 1, 'S', '4.01.01.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '01', '0003', null, null, null, null, 'COSTO DE PLATAFORMAS'                                             , 1, 'S', '4.01.01.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '01', '0004', null, null, null, null, 'COSTO DE REPUESTOS'                                               , 1, 'S', '4.01.01.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '01', '0005', null, null, null, null, 'COSTO DE SERVICIO TECNICO'                                        , 1, 'S', '4.01.01.0005', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '01', '0006', null, null, null, null, 'COSTO DE LEASING'                                                 , 1, 'S', '4.01.01.0006', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '01', '0007', null, null, null, null, 'COSTO DE ARRIENDO'                                                , 1, 'S', '4.01.01.0007', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0001', null, null, null, null, 'REMUNERACIONES'                                                   , 1, 'S', '4.01.02.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0002', null, null, null, null, 'COMISIONES POR VENTA'                                             , 1, 'S', '4.01.02.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0003', null, null, null, null, 'FINIQUITOS'                                                       , 1, 'S', '4.01.02.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0004', null, null, null, null, 'ASESORIA INFORMATICA'                                             , 1, 'S', '4.01.02.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0005', null, null, null, null, 'ASESORIA COMEX'                                                   , 1, 'S', '4.01.02.0005', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0006', null, null, null, null, 'ASESORIA DE MARKETING'                                            , 1, 'S', '4.01.02.0006', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0007', null, null, null, null, 'ASESORIA LEGAL'                                                   , 1, 'S', '4.01.02.0007', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0008', null, null, null, null, 'ASESORIA CONTABLE'                                                , 1, 'S', '4.01.02.0008', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0009', null, null, null, null, 'ASESORIA TECNICA'                                                 , 1, 'S', '4.01.02.0009', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0010', null, null, null, null, 'GASTOS DE PUBLICIDAD'                                             , 1, 'S', '4.01.02.0010', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0011', null, null, null, null, 'GASTOS DE REPRESENTACION'                                         , 1, 'S', '4.01.02.0011', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0012', null, null, null, null, 'VIAJES Y ESTADIAS'                                                , 1, 'S', '4.01.02.0012', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0013', null, null, null, null, 'FERIAS Y STAND'                                                   , 1, 'S', '4.01.02.0013', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0014', null, null, null, null, 'ARRIENDO DE OFICINAS'                                             , 1, 'S', '4.01.02.0014', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0015', null, null, null, null, 'COMBUSTIBLE'                                                      , 1, 'S', '4.01.02.0015', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0016', null, null, null, null, 'GASTOS DE OFICINA'                                                , 1, 'S', '4.01.02.0016', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0017', null, null, null, null, 'MANTENCION DE VEHICULOS'                                          , 1, 'S', '4.01.02.0017', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0018', null, null, null, null, 'TELEFONOS'                                                        , 1, 'S', '4.01.02.0018', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0019', null, null, null, null, 'AGUA'                                                             , 1, 'S', '4.01.02.0019', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0020', null, null, null, null, 'ELECTRICIDAD'                                                     , 1, 'S', '4.01.02.0020', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0021', null, null, null, null, 'GASTOS DE IMPRENTA'                                               , 1, 'S', '4.01.02.0021', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0022', null, null, null, null, 'SERVICIO DE ASEO'                                                 , 1, 'S', '4.01.02.0022', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0023', null, null, null, null, 'SERVICIO DE VIGILANCIA'                                           , 1, 'S', '4.01.02.0023', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0024', null, null, null, null, 'SEGUROS DE CHEQUES'                                               , 1, 'S', '4.01.02.0024', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0025', null, null, null, null, 'SEGUROS'                                                          , 1, 'S', '4.01.02.0025', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0026', null, null, null, null, 'COLACION'                                                         , 1, 'S', '4.01.02.0026', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0027', null, null, null, null, 'CORRESPONDENCIA'                                                  , 1, 'S', '4.01.02.0027', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0028', null, null, null, null, 'ALARMA DE SEGURIDAD'                                              , 1, 'S', '4.01.02.0028', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0029', null, null, null, null, 'TAG'                                                              , 1, 'S', '4.01.02.0029', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0030', null, null, null, null, 'ROPA DE TRABAJO'                                                  , 1, 'S', '4.01.02.0030', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0031', null, null, null, null, 'GASTOS DE TV CABLE'                                               , 1, 'S', '4.01.02.0031', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0032', null, null, null, null, 'GASTOS DE DICOM'                                                  , 1, 'S', '4.01.02.0032', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0033', null, null, null, null, 'GASTOS DE DOMINIO'                                                , 1, 'S', '4.01.02.0033', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0034', null, null, null, null, 'FLETES'                                                           , 1, 'S', '4.01.02.0034', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '02', '0035', null, null, null, null, 'GPS'                                                              , 1, 'S', '4.01.02.0035', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '03', '0001', null, null, null, null, 'GASTOS POR LEASING'                                               , 1, 'S', '4.01.03.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '03', '0002', null, null, null, null, 'GASTOS BANCARIOS'                                                 , 1, 'S', '4.01.03.0002', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '03', '0003', null, null, null, null, 'GASTOS POR PROTESTOS'                                             , 1, 'S', '4.01.03.0003', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '03', '0004', null, null, null, null, 'INTERESES BANCARIOS'                                              , 1, 'S', '4.01.03.0004', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '04', '0001', null, null, null, null, 'REAJUSTES'                                                        , 1, 'S', '4.01.04.0001', 1, current_timestamp, null, null, null, null);
  insert into cuentas_contables values (nextval('cuco_seq'), new.id, '4', '01', '05', '0001', null, null, null, null, 'IMPUESTO A LA RENTA'                                              , 1, 'S', '4.01.05.0001', 1, current_timestamp, null, null, null, null);

  update cuentas_contables
  set    imputable = 'N'
  where  idgrem    = new.id
  and    segmento4 = '0000'
  ;

  update cuentas_contables
  set    cuenta_desplegable = segmento1 || '.'  || segmento2 || '.'  || segmento3 || '.'  || segmento4
  where  idgrem             = new.id
  ;

  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'ALOJAMIENTO'                  , aux + 149, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'ARTÍCULOS ASEO Y LIMPIEZA'    , aux + 165, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'ARTÍCULOS ESCRITORIO'         , aux + 165, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'ATENCIÓN A CLIENTES'          , aux + 149, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'BENCINA AUTO PRESIDENCIA'     , aux + 160, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'COLACIÓN'                     , aux + 175, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'COMBUSTIBLES Y LUBRICANTES'   , aux + 160, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'ELEMENTOS TRABAJO Y SEGURIDAD', aux + 185, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'ESTACIONAMIENTO'              , aux + 149, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'FLETES'                       , aux + 183, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'FLORES PRESIDENCIA'           , aux + 160, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'FOTOCOPIAS'                   , aux + 165, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'GASTOS CASINO'                , aux + 185, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'GASTOS COMPUTACIONALES'       , aux + 153, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'GASTOS COMUNES'               , aux + 185, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'GASTOS DE REPRESENTACION'     , aux + 160, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'GASTOS VARIOS'                , aux + 185, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'HERRAMIENTAS MENORES'         , aux + 185, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'MOVILIZACIÓN'                 , aux + 149, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'PAGO PROVEEDORES'             , aux + 85 , 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'PASAJES AÉREOS'               , aux + 161, 1, current_timestamp, null, null, null, null);
  insert into conceptos_rendiciones_gastos values (nextval('corg_seq'), new.id,'PEAJES'                       , aux + 149, 1, current_timestamp, null, null, null, null);

  return new;
end;
$body$ LANGUAGE plpgsql;

\q

